# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend and Backend Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies and Build (Frontend)
      run: |
        cd frontend
        npm ci
        npm run build
    - name: Install Dependencies and Build (Backend)
      run: |
        cd backend
        npm ci
        npm run build
    - name: Check branch
      run: echo "Current branch is ${GITHUB_REF#refs/heads/}"
